insert into pistolas (nombre,pais,calibre) values ('Beretta 9000','italia',9)
insert into pistolas (nombre,pais,calibre) values ('Bersa BP9CC','Argentina',9)
insert into pistolas (nombre,pais,calibre) values ('Derringer','USA',11)
insert into pistolas (nombre,pais,calibre) values ('Desert Eagle','USA',10)
insert into pistolas (nombre,pais,calibre) values ('M15','USA',45)
